/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsServiceRouteImport } from './routes/terms-service'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ApiPublicAuthCallbackProviderRouteImport } from './routes/api/public/auth/callback.$provider'
import { Route as ApiPublicAuthStartProviderRouteImport } from './routes/api/public/auth/start.$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsServiceRoute = TermsServiceRouteImport.update({
  id: '/terms-service',
  path: '/terms-service',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthCallbackProviderRoute =
  ApiPublicAuthCallbackProviderRouteImport.update({
    id: '/api/public/auth/callback/$provider',
    path: '/api/public/auth/callback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthStartProviderRoute =
  ApiPublicAuthStartProviderRouteImport.update({
    id: '/api/public/auth/start/$provider',
    path: '/api/public/auth/start/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/getting-started': typeof GettingStartedRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/terms-service': typeof TermsServiceRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/public/auth/callback/$provider': typeof ApiPublicAuthCallbackProviderRoute
  '/api/public/auth/start/$provider': typeof ApiPublicAuthStartProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/getting-started': typeof GettingStartedRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/terms-service': typeof TermsServiceRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/public/auth/callback/$provider': typeof ApiPublicAuthCallbackProviderRoute
  '/api/public/auth/start/$provider': typeof ApiPublicAuthStartProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/getting-started': typeof GettingStartedRoute
  '/import': typeof ImportRoute
  '/integrations': typeof IntegrationsRoute
  '/library': typeof LibraryRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/settings': typeof SettingsRoute
  '/terms-service': typeof TermsServiceRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/api/public/auth/callback/$provider': typeof ApiPublicAuthCallbackProviderRoute
  '/api/public/auth/start/$provider': typeof ApiPublicAuthStartProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/faq'
    | '/getting-started'
    | '/import'
    | '/integrations'
    | '/library'
    | '/privacy-policy'
    | '/settings'
    | '/terms-service'
    | '/workspace'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/project/$projectId'
    | '/api/public/auth/callback/$provider'
    | '/api/public/auth/start/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/faq'
    | '/getting-started'
    | '/import'
    | '/integrations'
    | '/library'
    | '/privacy-policy'
    | '/settings'
    | '/terms-service'
    | '/workspace'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/project/$projectId'
    | '/api/public/auth/callback/$provider'
    | '/api/public/auth/start/$provider'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/faq'
    | '/getting-started'
    | '/import'
    | '/integrations'
    | '/library'
    | '/privacy-policy'
    | '/settings'
    | '/terms-service'
    | '/workspace'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/project/$projectId'
    | '/api/public/auth/callback/$provider'
    | '/api/public/auth/start/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  GettingStartedRoute: typeof GettingStartedRoute
  ImportRoute: typeof ImportRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LibraryRoute: typeof LibraryRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SettingsRoute: typeof SettingsRoute
  TermsServiceRoute: typeof TermsServiceRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  ApiPublicAuthCallbackProviderRoute: typeof ApiPublicAuthCallbackProviderRoute
  ApiPublicAuthStartProviderRoute: typeof ApiPublicAuthStartProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-service': {
      id: '/terms-service'
      path: '/terms-service'
      fullPath: '/terms-service'
      preLoaderRoute: typeof TermsServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/callback/$provider': {
      id: '/api/public/auth/callback/$provider'
      path: '/api/public/auth/callback/$provider'
      fullPath: '/api/public/auth/callback/$provider'
      preLoaderRoute: typeof ApiPublicAuthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/start/$provider': {
      id: '/api/public/auth/start/$provider'
      path: '/api/public/auth/start/$provider'
      fullPath: '/api/public/auth/start/$provider'
      preLoaderRoute: typeof ApiPublicAuthStartProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  GettingStartedRoute: GettingStartedRoute,
  ImportRoute: ImportRoute,
  IntegrationsRoute: IntegrationsRoute,
  LibraryRoute: LibraryRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SettingsRoute: SettingsRoute,
  TermsServiceRoute: TermsServiceRoute,
  WorkspaceRoute: WorkspaceRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  ApiPublicAuthCallbackProviderRoute: ApiPublicAuthCallbackProviderRoute,
  ApiPublicAuthStartProviderRoute: ApiPublicAuthStartProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
